#! /bin/sh
#
# Take simulation results stored in data.%04d.dat and calls
# povray to render each scene.
# The data files are generated by 'liquid' physics simulation
# program.
#
# Author: Rodrigo Setti <rodrigosetti@gmail.com>
#

# Create images directory if it doesn't exists
mkdir -p images

# For each data file frame number
for N in $(ls data/*.dat | sed 's/data\/\([0-9]\+\)\.dat/\1/' | sort); do

    # replace %FRAMEDATAFILENAME% placeholder in template with data filename
    # into a new file called frame.pov
    sed "s/%FRAMEDATAFILENAME%/data\/$N.dat/" frame.pov.template > frame.pov

    # Run povray to render frame and save to a numbered image
    povray +Iframe.pov +Oimages/$N.png +W800 +H600 -D -V +A
done

# Delete temporary povray file created from template
rm -f frame.pov

